import { Configuration, OpenAIApi } from "openai";

export async function POST(request) {
  const { story } = await request.json();

  const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
  });

  const openai = new OpenAIApi(configuration);

  try {
    const response = await openai.createChatCompletion({
      model: "gpt-3.5-turbo",
      messages: [
        {
          role: "user",
          content: `Please generate a unique children's story book consisting of multiple pages, each with short sentences. For each page, please provide the following:
          Page number, Text (a short sentence or two that tells the story), Image prompt (a description of an image that could be generated by an AI image generator, such as DALL-E 2, to accompany the text).  The story should be based on the following prompt: 'A princess and 3 bears.'. Please ensure that the story flows well and is suitable for young children. The response should be a JSON array, and each object should have the following properties: PAGE, TEXT, PROMPT. `,
        },
      ],
    });

    const fullStory = response.data.choices[0].message.content;
    const arr = JSON.parse(JSON.stringify(JSON.parse(fullStory)));

    return new Response(JSON.stringify({ data: arr }));
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }));
  }
}
